version: 3.8


services:
  flask:
    build: ./flaskapp
    container_name: flaskDcokerJenkinsApp
    restart: always
    port:
      - 5000:5000
  

  nginx:
    build: ./nginx
    container_name: nGnix5000
    restart: always
    port:
      - 80:80
    depends_on:
      - flask
